---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: mediawiki
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ocs-external-storagecluster-cephfs
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: postgresql
stringData:
  database-name: wiki
  database-password: t4m5GjNUTbCXygLf
  database-user: wiki
---
apiVersion: v1
kind: Secret
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: mediawiki
stringData:
  admin-user: admin
  admin-password: ZsgbUt8k7TnqrT34
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: postgresql
spec:
  serviceName: postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/part-of: mediawiki
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgresql
        app.kubernetes.io/part-of: mediawiki
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - capabilities: {}
        env:
        - name: POSTGRESQL_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: postgresql
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: postgresql
        - name: POSTGRESQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgresql
        image: image-registry.openshift-image-registry.svc:5000/openshift/postgresql:13-el9
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 10m
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: postgresql
  volumeClaimTemplates:
  - metadata:
      name: postgresql
      labels:
        app.kubernetes.io/part-of: mediawiki
        app.kubernetes.io/name: postgresql
    spec:
      storageClassName: ocs-external-storagecluster-ceph-rbd
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: postgresql
spec:
  ports:
  - name: postgresql
    nodePort: 0
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/part-of: mediawiki
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: mediawiki
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mediawiki
      app.kubernetes.io/part-of: mediawiki
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mediawiki
        app.kubernetes.io/part-of: mediawiki
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - image: registry.ocp4.example.com:8443/redhattraining/mediawiki:do380
        name: mediawiki
        env:
        - name: MEDIAWIKI_DB_SCHEMA
          value: mediawiki
        - name: MEDIAWIKI_SITE_NAME
          value: DO380 Team Wiki
        - name: MEDIAWIKI_SITE_LANG
          value: en
        - name: MEDIAWIKI_SITE_SERVER
          value: https://mediawiki-mediawiki.apps.ocp4.example.com
        - name: MEDIAWIKI_DB_TYPE
          value: postgres
        - name: MEDIAWIKI_DB_HOST
          value: postgresql
        - name: MEDIAWIKI_DB_PORT
          value: '5432'
        - name: MEDIAWIKI_LOGO
          value: '/images/c/ca/Mw_logo.png'
        - name: MEDIAWIKI_ADMIN_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: mediawiki
        - name: MEDIAWIKI_ADMIN_PASS
          valueFrom:
            secretKeyRef:
              key: admin-password
              name: mediawiki
        - name: MEDIAWIKI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: postgresql
        - name: MEDIAWIKI_DB_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: postgresql
        - name: MEDIAWIKI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: postgresql
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /api.php?action=query&meta=siteinfo&format=json
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 1m
        volumeMounts:
        - name: mediawiki
          mountPath: /data
      volumes:
      - name: mediawiki
        persistentVolumeClaim:
          claimName: mediawiki
---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: mediawiki
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: mediawiki
    app.kubernetes.io/part-of: mediawiki
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mediawiki
  labels:
    app.kubernetes.io/part-of: mediawiki
    app.kubernetes.io/name: mediawiki
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: mediawiki
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge